name: Upload Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SOURCE_DIR: 'website'  # or '.' if not in subfolder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete  # ✅ fixed line (no --acl)


      
